services:
  mysql:
    image: mysql:8.0
    container_name: webcrawler-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawlerpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webcrawler-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: webcrawler-backend
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=crawler
      - DB_PASSWORD=crawlerpassword
      - DB_NAME=webcrawler
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - webcrawler-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: webcrawler-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webcrawler-network

volumes:
  mysql_data:

networks:
  webcrawler-network:
    driver: bridge
